width = 60
height = 15
map_offset = 0
player_pos = [2, 12]
obstacles = []
platforms = []
secret_items = []
bats = []
level_up_items = []
game_over = false
score = 0
points = 0
item_count = 0
level = 1
jumping = false
fireball_active = false
jump_height = 3
jump_progress = 0
gravity_delay = 0.05
checkpoint_interval = 20
next_obstacle_time = 0
next_bat_time = 0
last_checkpoint = 0
save_file = "save_data.csv"
player_name = ""
fireball_position = 0